### ISSUE TITLE
Add Not Without My Dolphin from The Boys

### ISSUE THREAD

**Issue by matt-narvar** [lynnandtonic/nestflix.fun#505]
Please add as much of the following info as you can:

Title: Not Without My Dolphin

Type (film/tv show): Film

Film or show in which it appears: The Boys

Is the parent film/show streaming anywhere? Amazon Prime

About when in the parent film/show does it appear? Season 3 Episode 2. You can also just find the fake trailer on youtube.

Actual footage of the film/show can be seen (yes/no)? Yes

**Comment by HarleysTwin** [comment]
Here is that aforementioned trailer (I'm not screenshotting it because I don't know what parts are from _The Boys_ and what parts are from the film specifically: https://www.youtube.com/watch?v=p6DzG8rPdjE

Production Company: Vought Studios

Channel: Vtv (Television for Women)

Starring: The Deep, Billy Zane

**Comment by lynnandtonic** [comment]
Thank you!! https://nestflix.fun/not-without-my-dolphin/
