### ISSUE TITLE
Foreign Titles?

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#513]
Is Nestflix interested in posting titles from foreign shows/films? I’ve noticed all the titles on the site are English/American based, even though foreign suggestions have been made. No shade/criticism or anything. Just wondering if that’s a filter that should be to be made when making suggestions.

**Comment by lynnandtonic** [comment]
Hey! Thank you so much for all of your submissions. I really appreciate it!

I’m definitely open to adding foreign shows/films (as long as I can stream them somewhere). 

To be honest though, I still have over 500 titles that have been submitted. I’ve been prioritizing movies/shows I’m familiar with since each entry takes a decent amount of time.

I hope I can get to all the suggestions but realistically some suggestions just may never make it on the site, unfortunately!
